name: First-workflow
on: workflow-dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - print Greeting
        run: echo "Hello!"
      - print print Goodbye
        run: echo "Done! bye"
